<? if ($cnf_menuCalendar) { ?><a href="/calendar/" class="list-group-item">Calendar of Events</a><? } ?>
<? if ($cnf_menuOfficers) { ?><a href="/officers/" class="list-group-item">Lodge Officers</a><? } ?>
<? if ($cnf_menuPastMasters) { ?><a href="/years/" class="list-group-item">Past Masters Gallery</a><? } ?>
<? if ($cnf_menuNewsletters) { ?><a href="/museum/newsletters/" class="list-group-item">Newsletters</a><? } ?>
<? if ($cnf_menuHistory) { ?><a href="/history/" class="list-group-item">Lodge History</a><? } ?>
<? if ($cnf_menuVeterans) { ?><a href="/veterans/" class="list-group-item">Masonic Veterans</a><? } ?>
<? if ($cnf_menuMemoriam) { ?><a href="/memorial/" class="list-group-item">In Memoriam</a><? } ?>
<? if ($cnf_menuMasonOfTheYear) { ?><a href="/moty/" class="list-group-item">Mason of the Year</a><? } ?>
<? if ($cnf_menuLifeMembers) { ?><a href="/lmip/" class="list-group-item">Life Members in Perpetuity</a><? } ?>
<? if ($cnf_menuAwards) { ?><a href="/awards/" class="list-group-item">Awards and Recognition</a><? } ?>
