<?php
// basic information
$cnf_lodgeNameNumber = "Internet Lodge No. 123";
$cnf_lodgeName = "Internet Lodge";
$cnf_lodgeAddress = "123 Main Street";
$cnf_lodgeCityStateZip = "Masonville, VA 12345";
$cnf_statedMeetings = "2<sup>nd</sup> Tuesday at 7:00PM, Dinner at 6:00PM";
$cnf_workMeetings = "7:00PM";

$cnf_webmasterName = "John Doe";
$cnf_webmasterEmail = "webmaster@internetlodge123.org";

$cnf_mainColor = "orange";
$cnf_mainColorDark = "darkorange";

// lodge description shown on home page
$cnf_lodgeDescription = "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sapien
diam, cursus in fermentum vel, iaculis vel turpis. Morbi eget nibh
quis enim rutrum tincidunt. Sed rutrum, urna a placerat convallis,
eros tellus finibus lectus, nec lobortis nisl turpis at
augue. Vestibulum ante ipsum primis in faucibus orci luctus et
ultrices posuere cubilia Curae; Proin id bibendum tortor. Donec metus
dolor, hendrerit quis neque quis, imperdiet dapibus nunc. Aenean vel
est vel risus ultricies tristique et at arcu. Ut id elit blandit,
lacinia metus eget, fermentum neque. Nam non orci tincidunt eros
pellentesque iaculis ac vel odio. Vivamus sit amet fringilla quam, in
egestas nulla.
";

// menu items to show
$cnf_menuCalendar = true;
$cnf_menuOfficers = true;
$cnf_menuPastMasters = true;
$cnf_menuNewsletters = true;
$cnf_menuHistory = true;
$cnf_menuVeterans = true;
$cnf_menuMemoriam = true;
$cnf_menuMasonOfTheYear = true;
$cnf_menuLifeMembers = true;
$cnf_menuAwards = true;

?>